import Head from "next/head";

function MetaData(props) {
    return (  <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/vercel.svg" />
            </Head>
    );
}

export default MetaData;